export const C = {
  bg:         "#F5F3EE",
  bgDeep:     "#EDEAE2",
  surface:    "#FFFFFF",
  surfaceAlt: "#F9F8F5",
  border:     "#D9D5CB",
  borderMid:  "#C4BFB3",
  ink:        "#1C1A17",
  inkMid:     "#5C5850",
  inkDim:     "#9C9890",
  orange:      "#D35400", 
  orangeLight: "#FDEBD0",
  orangeMid:   "#E67E22",
  orangeDim:   "#A04000",
  red:        "#C0392B",
  redLight:   "#FBEAE8",
  amber:      "#B7650A",
  amberLight: "#FDF3E3",
  blue:       "#1A5276",
  blueLight:  "#EAF2FB",
  teal:       "#0E6655",
};

const G_X = "0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798";
const G_Y = "0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8";
export const CURVES = ["secp256k1", "p256", "p384"];
export const GROUPS = ["modp2048", "modp3072", "modp4096"];

export const OPS = {
  field: [
    { id:"element", label:"Create Element", desc:"Validate & normalise a value into GF(p)",
      method:"POST", path:"/api/field/element",
      fields:[
        {key:"prime",label:"Prime p",placeholder:"223",hint:"decimal or 0x hex"},
        {key:"value",label:"Value a",placeholder:"192",hint:"reduced mod p"},
      ]},
    { id:"add", label:"Add", desc:"a + b mod p", method:"POST", path:"/api/field/add",
      fields:[{key:"prime",label:"Prime p",placeholder:"223"},{key:"a",label:"a",placeholder:"192"},{key:"b",label:"b",placeholder:"105"}]},
    { id:"sub", label:"Subtract", desc:"a − b mod p", method:"POST", path:"/api/field/sub",
      fields:[{key:"prime",label:"Prime p",placeholder:"223"},{key:"a",label:"a",placeholder:"192"},{key:"b",label:"b",placeholder:"105"}]},
    { id:"mul", label:"Multiply", desc:"a × b mod p", method:"POST", path:"/api/field/mul",
      fields:[{key:"prime",label:"Prime p",placeholder:"223"},{key:"a",label:"a",placeholder:"192"},{key:"b",label:"b",placeholder:"105"}]},
    { id:"div", label:"Divide", desc:"a × b⁻¹ mod p", method:"POST", path:"/api/field/div",
      fields:[{key:"prime",label:"Prime p",placeholder:"223"},{key:"a",label:"Numerator a",placeholder:"192"},{key:"b",label:"Divisor b",placeholder:"105"}]},
    { id:"pow", label:"Power", desc:"base ^ exp mod p", method:"POST", path:"/api/field/pow",
      fields:[{key:"prime",label:"Prime p",placeholder:"223"},{key:"base",label:"Base",placeholder:"192"},{key:"exp",label:"Exponent",placeholder:"3",hint:"negative → inverse"}]},
    { id:"inverse", label:"Inverse", desc:"Multiplicative inverse a⁻¹ in GF(p)", method:"POST", path:"/api/field/inverse",
      fields:[{key:"prime",label:"Prime p",placeholder:"223"},{key:"value",label:"a",placeholder:"192"}]},
    { id:"neg", label:"Negate", desc:"Additive inverse p − a mod p", method:"POST", path:"/api/field/neg",
      fields:[{key:"prime",label:"Prime p",placeholder:"223"},{key:"value",label:"a",placeholder:"192"}]},
  ],
  ecc: [
    { id:"curves",     label:"List Curves",      desc:"All available named curves",
      method:"GET", path:"/api/ecc/curves", fields:[]},
    { id:"curve_info", label:"Curve Info",       desc:"Parameters for a specific curve",
      method:"GET", path:"/api/ecc/curves/:name",
      fields:[{key:"name",label:"Curve",type:"select",options:CURVES}]},
    { id:"generator",  label:"Generator Point G", desc:"Base point G coordinates",
      method:"GET", path:"/api/ecc/curves/:name/generator",
      fields:[{key:"name",label:"Curve",type:"select",options:CURVES}]},
    { id:"validate",   label:"Validate Point",    desc:"Check whether (x, y) lies on the curve",
      method:"POST", path:"/api/ecc/point/validate",
      fields:[
        {key:"curve",label:"Curve",type:"select",options:CURVES},
        {key:"x",label:"x coordinate",placeholder:G_X,default:G_X,hint:"pre-filled: G·x"},
        {key:"y",label:"y coordinate",placeholder:G_Y,default:G_Y},
      ]},
    { id:"point_add",  label:"Point Addition",    desc:"P₁ + P₂ on the curve",
      method:"POST", path:"/api/ecc/point/add",
      fields:[
        {key:"curve",label:"Curve",type:"select",options:CURVES},
        {key:"x1",label:"P₁ x",placeholder:G_X,default:G_X,hint:"G + G = 2G"},
        {key:"y1",label:"P₁ y",placeholder:G_Y,default:G_Y},
        {key:"x2",label:"P₂ x",placeholder:G_X,default:G_X},
        {key:"y2",label:"P₂ y",placeholder:G_Y,default:G_Y},
      ]},
    { id:"scalar_mul", label:"Scalar Multiply",   desc:"k × P — leave P blank for G",
      method:"POST", path:"/api/ecc/scalar_mul",
      fields:[
        {key:"curve",label:"Curve",type:"select",options:CURVES},
        {key:"k",label:"Scalar k",placeholder:"2",default:"2",hint:"decimal or 0x hex"},
        {key:"x",label:"P x (optional)",placeholder:"leave blank to use G"},
        {key:"y",label:"P y (optional)",placeholder:"leave blank to use G"},
      ]},
  ],
  utils: [
    { id:"is_prime",      label:"Is Prime?",      desc:"Miller-Rabin primality test",
      method:"POST", path:"/api/utils/is_prime",
      fields:[{key:"n",label:"n",placeholder:"0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F",hint:"decimal or 0x hex"}]},
    { id:"next_prime",    label:"Next Prime",     desc:"Smallest prime ≥ n",
      method:"POST", path:"/api/utils/next_prime",
      fields:[{key:"n",label:"n",placeholder:"100"}]},
    { id:"generate_prime",label:"Generate Prime", desc:"Random prime of exactly n bits",
      method:"POST", path:"/api/utils/generate_prime",
      fields:[{key:"bits",label:"Bit length",placeholder:"256",hint:"2 – 4096"}]},
    { id:"mod_inverse",   label:"Modular Inverse",desc:"Inverse of a (mod m)",
      method:"POST", path:"/api/utils/mod_inverse",
      fields:[{key:"a",label:"a",placeholder:"3"},{key:"m",label:"Modulus m",placeholder:"11"}]},
    { id:"xgcd",          label:"Extended GCD",   desc:"gcd(a, b) = a·x + b·y",
      method:"POST", path:"/api/utils/xgcd",
      fields:[{key:"a",label:"a",placeholder:"35"},{key:"b",label:"b",placeholder:"15"}]},
  ],
  dhke: [
    { id:"keypair",       label:"Generate Key Pair",   desc:"Fresh DHKE key pair over RFC 3526 MODP group",
      method:"POST", path:"/api/crypto/dhke/keypair",
      note:"Run this twice — once for each party. Keep private_key.x secret, share public_key.y.",
      fields:[{key:"group",label:"Group",type:"select",options:GROUPS,default:"modp2048"}]},
    { id:"shared_secret", label:"Shared Secret",       desc:"g^(xy) mod p — both parties compute the same value",
      method:"POST", path:"/api/crypto/dhke/shared_secret",
      note:"Paste your private key fields and the peer's public_key.y.",
      fields:[
        {key:"private_group",label:"Group",type:"select",options:GROUPS,default:"modp2048"},
        {key:"private_x",    label:"Your private_key.x",  placeholder:"(from /keypair)"},
        {key:"private_p",    label:"Your private_key.p",  placeholder:"(from /keypair)"},
        {key:"private_g",    label:"Your private_key.g",  placeholder:"2",default:"2"},
        {key:"peer_y",       label:"Peer's public_key.y", placeholder:"(from peer's /keypair)"},
      ]},
    { id:"derive_key",    label:"Derive Key",           desc:"SHA-256 KDF → symmetric key bytes",
      method:"POST", path:"/api/crypto/dhke/derive_key",
      note:"Both parties run this with the same shared secret to get an identical AES key.",
      fields:[
        {key:"secret",       label:"Shared secret",     placeholder:"(decimal from /shared_secret)"},
        {key:"secret_group", label:"Group",             type:"select",options:GROUPS,default:"modp2048"},
        {key:"length",       label:"Key length (bytes)", placeholder:"32",default:"32",hint:"1 – 64"},
      ]},
  ],
};

export const SECTIONS = {
  field: { label:"Prime Field",    sub:"𝔽ₚ",     icon:"𝔽" },
  ecc:   { label:"Elliptic Curves",sub:"ECC",    icon:"𝔼" },
  utils: { label:"Number Theory",  sub:"ℕ",      icon:"∂" },
  dhke:  { label:"Diffie-Hellman", sub:"DHKE",   icon:"⇄" },
};